//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConLine {
    
    
    public partial class Intro {
        
        /// <summary>
        /// UCProductListMostSold control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ConLine.UserControls.UCProductList UCProductListMostSold;
        
        /// <summary>
        /// UCProductListNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ConLine.UserControls.UCProductList UCProductListNew;
        
        /// <summary>
        /// UCProductListDiscount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ConLine.UserControls.UCProductList UCProductListDiscount;
        
        /// <summary>
        /// UCProductListSepcial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ConLine.UserControls.UCProductList UCProductListSepcial;
    }
}
