#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConLine.Old_App_Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ConLine")]
	public partial class CouponsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCoupons(Coupons instance);
    partial void UpdateCoupons(Coupons instance);
    partial void DeleteCoupons(Coupons instance);
    #endregion
		
		public CouponsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConLineConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CouponsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CouponsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CouponsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CouponsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vCoupons> vCoupons
		{
			get
			{
				return this.GetTable<vCoupons>();
			}
		}
		
		public System.Data.Linq.Table<Coupons> Coupons
		{
			get
			{
				return this.GetTable<Coupons>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vCoupons")]
	public partial class vCoupons
	{
		
		private int _Code;
		
		private string _ID;
		
		private string _PostCode;
		
		public vCoupons()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostCode", DbType="VarChar(50)")]
		public string PostCode
		{
			get
			{
				return this._PostCode;
			}
			set
			{
				if ((this._PostCode != value))
				{
					this._PostCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Coupons")]
	public partial class Coupons : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _ID;
		
		private System.Nullable<bool> _Used;
		
		private System.Nullable<int> _CouponCount;
		
		private System.Nullable<int> _HCCouponTypeCode;
		
		private System.Nullable<int> _Val;
		
		private System.Nullable<int> _HCCouponStatusCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnUsedChanging(System.Nullable<bool> value);
    partial void OnUsedChanged();
    partial void OnCouponCountChanging(System.Nullable<int> value);
    partial void OnCouponCountChanged();
    partial void OnHCCouponTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCCouponTypeCodeChanged();
    partial void OnValChanging(System.Nullable<int> value);
    partial void OnValChanged();
    partial void OnHCCouponStatusCodeChanging(System.Nullable<int> value);
    partial void OnHCCouponStatusCodeChanged();
    #endregion
		
		public Coupons()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Used", DbType="Bit")]
		public System.Nullable<bool> Used
		{
			get
			{
				return this._Used;
			}
			set
			{
				if ((this._Used != value))
				{
					this.OnUsedChanging(value);
					this.SendPropertyChanging();
					this._Used = value;
					this.SendPropertyChanged("Used");
					this.OnUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouponCount", DbType="Int")]
		public System.Nullable<int> CouponCount
		{
			get
			{
				return this._CouponCount;
			}
			set
			{
				if ((this._CouponCount != value))
				{
					this.OnCouponCountChanging(value);
					this.SendPropertyChanging();
					this._CouponCount = value;
					this.SendPropertyChanged("CouponCount");
					this.OnCouponCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCCouponTypeCode", DbType="Int")]
		public System.Nullable<int> HCCouponTypeCode
		{
			get
			{
				return this._HCCouponTypeCode;
			}
			set
			{
				if ((this._HCCouponTypeCode != value))
				{
					this.OnHCCouponTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCCouponTypeCode = value;
					this.SendPropertyChanged("HCCouponTypeCode");
					this.OnHCCouponTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Val", DbType="Int")]
		public System.Nullable<int> Val
		{
			get
			{
				return this._Val;
			}
			set
			{
				if ((this._Val != value))
				{
					this.OnValChanging(value);
					this.SendPropertyChanging();
					this._Val = value;
					this.SendPropertyChanged("Val");
					this.OnValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCCouponStatusCode", DbType="Int")]
		public System.Nullable<int> HCCouponStatusCode
		{
			get
			{
				return this._HCCouponStatusCode;
			}
			set
			{
				if ((this._HCCouponStatusCode != value))
				{
					this.OnHCCouponStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCCouponStatusCode = value;
					this.SendPropertyChanged("HCCouponStatusCode");
					this.OnHCCouponStatusCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
